# Generated by Django 2.2.2 on 2019-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_status',
            field=models.CharField(default='Processing', max_length=30),
        ),
    ]
